name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is. Screenshots welcome!"
    validations:
      required: true
  - type: input
    id: heidisql_version
    attributes:
      label: HeidiSQL version
      placeholder: "Example: 12.8.0.6908"
    validations:
      required: true
  - type: input
    id: database_software
    attributes:
      label: Database server version
      placeholder: "Example: MariaDB 10.3.27, or just '-' if irrelevant"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction recipe
      placeholder: "Instructions for reproducing the problem"
    validations:
      required: true
  - type: textarea
    id: error_log
    attributes:
      label: Error/Backtrace
      placeholder: "Optional, attach or paste crash report here"
      render: shell
