unit vktable;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils, LCLType;

type
  TVirtualKeyInfo = record
    Code: Word;
    Name: string;
    Value: Word;
  end;
  function GetVKIndexByCode(Code: Word): Integer;

const
  VKcodes: array[0..192] of TVirtualKeyInfo = (
    (Code: VK_UNKNOWN;         Name: 'UNKNOWN';          Value: 0),
    (Code: VK_LBUTTON;         Name: 'LBUTTON';          Value: 1),
    (Code: VK_RBUTTON;         Name: 'RBUTTON';          Value: 2),
    (Code: VK_CANCEL;          Name: 'CANCEL';           Value: 3),
    (Code: VK_MBUTTON;         Name: 'MBUTTON';          Value: 4),
    (Code: VK_XBUTTON1;        Name: 'XBUTTON1';         Value: 5),
    (Code: VK_XBUTTON2;        Name: 'XBUTTON2';         Value: 6),
    (Code: VK_BACK;            Name: 'BACK';             Value: 8),
    (Code: VK_TAB;             Name: 'TAB';              Value: 9),
    (Code: VK_CLEAR;           Name: 'CLEAR';            Value: 12),
    (Code: VK_RETURN;          Name: 'RETURN';           Value: 13),
    (Code: VK_SHIFT;           Name: 'SHIFT';            Value: 16),
    (Code: VK_CONTROL;         Name: 'CONTROL';          Value: 17),
    (Code: VK_MENU;            Name: 'MENU';             Value: 18),
    (Code: VK_PAUSE;           Name: 'PAUSE';            Value: 19),
    (Code: VK_CAPITAL;         Name: 'CAPITAL';          Value: 20),
    (Code: VK_KANA;            Name: 'KANA';             Value: 21),
    (Code: VK_HANGUL;          Name: 'HANGUL';           Value: 21),
    (Code: VK_JUNJA;           Name: 'JUNJA';            Value: 23),
    (Code: VK_FINAL;           Name: 'FINAL';            Value: 24),
    (Code: VK_HANJA;           Name: 'HANJA';            Value: 25),
    (Code: VK_KANJI;           Name: 'KANJI';            Value: 25),
    (Code: VK_ESCAPE;          Name: 'ESCAPE';           Value: 27),
    (Code: VK_CONVERT;         Name: 'CONVERT';          Value: 28),
    (Code: VK_NONCONVERT;      Name: 'NONCONVERT';       Value: 29),
    (Code: VK_ACCEPT;          Name: 'ACCEPT';           Value: 30),
    (Code: VK_MODECHANGE;      Name: 'MODECHANGE';       Value: 31),
    (Code: VK_SPACE;           Name: 'SPACE';            Value: 32),
    (Code: VK_PRIOR;           Name: 'PRIOR';            Value: 33),
    (Code: VK_NEXT;            Name: 'NEXT';             Value: 34),
    (Code: VK_END;             Name: 'END';              Value: 35),
    (Code: VK_HOME;            Name: 'HOME';             Value: 36),
    (Code: VK_LEFT;            Name: 'LEFT';             Value: 37),
    (Code: VK_UP;              Name: 'UP';               Value: 38),
    (Code: VK_RIGHT;           Name: 'RIGHT';            Value: 39),
    (Code: VK_DOWN;            Name: 'DOWN';             Value: 40),
    (Code: VK_SELECT;          Name: 'SELECT';           Value: 41),
    (Code: VK_PRINT;           Name: 'PRINT';            Value: 42),
    (Code: VK_EXECUTE;         Name: 'EXECUTE';          Value: 43),
    (Code: VK_SNAPSHOT;        Name: 'SNAPSHOT';         Value: 44),
    (Code: VK_INSERT;          Name: 'INSERT';           Value: 45),
    (Code: VK_DELETE;          Name: 'DELETE';           Value: 46),
    (Code: VK_HELP;            Name: 'HELP';             Value: 47),
    (Code: VK_0;               Name: '0';                Value: $30),
    (Code: VK_1;               Name: '1';                Value: $31),
    (Code: VK_2;               Name: '2';                Value: $32),
    (Code: VK_3;               Name: '3';                Value: $33),
    (Code: VK_4;               Name: '4';                Value: $34),
    (Code: VK_5;               Name: '5';                Value: $35),
    (Code: VK_6;               Name: '6';                Value: $36),
    (Code: VK_7;               Name: '7';                Value: $37),
    (Code: VK_8;               Name: '8';                Value: $38),
    (Code: VK_9;               Name: '9';                Value: $39),
    (Code: VK_A;               Name: 'A';                Value: $41),
    (Code: VK_B;               Name: 'B';                Value: $42),
    (Code: VK_C;               Name: 'C';                Value: $43),
    (Code: VK_D;               Name: 'D';                Value: $44),
    (Code: VK_E;               Name: 'E';                Value: $45),
    (Code: VK_F;               Name: 'F';                Value: $46),
    (Code: VK_G;               Name: 'G';                Value: $47),
    (Code: VK_H;               Name: 'H';                Value: $48),
    (Code: VK_I;               Name: 'I';                Value: $49),
    (Code: VK_J;               Name: 'J';                Value: $4A),
    (Code: VK_K;               Name: 'K';                Value: $4B),
    (Code: VK_L;               Name: 'L';                Value: $4C),
    (Code: VK_M;               Name: 'M';                Value: $4D),
    (Code: VK_N;               Name: 'N';                Value: $4E),
    (Code: VK_O;               Name: 'O';                Value: $4F),
    (Code: VK_P;               Name: 'P';                Value: $50),
    (Code: VK_Q;               Name: 'Q';                Value: $51),
    (Code: VK_R;               Name: 'R';                Value: $52),
    (Code: VK_S;               Name: 'S';                Value: $53),
    (Code: VK_T;               Name: 'T';                Value: $54),
    (Code: VK_U;               Name: 'U';                Value: $55),
    (Code: VK_V;               Name: 'V';                Value: $56),
    (Code: VK_W;               Name: 'W';                Value: $57),
    (Code: VK_X;               Name: 'X';                Value: $58),
    (Code: VK_Y;               Name: 'Y';                Value: $59),
    (Code: VK_Z;               Name: 'Z';                Value: $5A),
    (Code: VK_LWIN;            Name: 'LWIN';             Value: $5B),
    (Code: VK_RWIN;            Name: 'RWIN';             Value: $5C),
    (Code: VK_APPS;            Name: 'APPS';             Value: $5D),
    (Code: VK_SLEEP;           Name: 'SLEEP';            Value: $5F),
    (Code: VK_NUMPAD0;         Name: 'NUMPAD0';          Value: 96),
    (Code: VK_NUMPAD1;         Name: 'NUMPAD1';          Value: 97),
    (Code: VK_NUMPAD2;         Name: 'NUMPAD2';          Value: 98),
    (Code: VK_NUMPAD3;         Name: 'NUMPAD3';          Value: 99),
    (Code: VK_NUMPAD4;         Name: 'NUMPAD4';          Value: 100),
    (Code: VK_NUMPAD5;         Name: 'NUMPAD5';          Value: 101),
    (Code: VK_NUMPAD6;         Name: 'NUMPAD6';          Value: 102),
    (Code: VK_NUMPAD7;         Name: 'NUMPAD7';          Value: 103),
    (Code: VK_NUMPAD8;         Name: 'NUMPAD8';          Value: 104),
    (Code: VK_NUMPAD9;         Name: 'NUMPAD9';          Value: 105),
    (Code: VK_MULTIPLY;        Name: 'MULTIPLY';         Value: 106),
    (Code: VK_ADD;             Name: 'ADD';              Value: 107),
    (Code: VK_SEPARATOR;       Name: 'SEPARATOR';        Value: 108),
    (Code: VK_SUBTRACT;        Name: 'SUBTRACT';         Value: 109),
    (Code: VK_DECIMAL;         Name: 'DECIMAL';          Value: 110),
    (Code: VK_DIVIDE;          Name: 'DIVIDE';           Value: 111),
    (Code: VK_F1;              Name: 'F1';               Value: 112),
    (Code: VK_F2;              Name: 'F2';               Value: 113),
    (Code: VK_F3;              Name: 'F3';               Value: 114),
    (Code: VK_F4;              Name: 'F4';               Value: 115),
    (Code: VK_F5;              Name: 'F5';               Value: 116),
    (Code: VK_F6;              Name: 'F6';               Value: 117),
    (Code: VK_F7;              Name: 'F7';               Value: 118),
    (Code: VK_F8;              Name: 'F8';               Value: 119),
    (Code: VK_F9;              Name: 'F9';               Value: 120),
    (Code: VK_F10;             Name: 'F10';              Value: 121),
    (Code: VK_F11;             Name: 'F11';              Value: 122),
    (Code: VK_F12;             Name: 'F12';              Value: 123),
    (Code: VK_F13;             Name: 'F13';              Value: 124),
    (Code: VK_F14;             Name: 'F14';              Value: 125),
    (Code: VK_F15;             Name: 'F15';              Value: 126),
    (Code: VK_F16;             Name: 'F16';              Value: 127),
    (Code: VK_F17;             Name: 'F17';              Value: 128),
    (Code: VK_F18;             Name: 'F18';              Value: 129),
    (Code: VK_F19;             Name: 'F19';              Value: 130),
    (Code: VK_F20;             Name: 'F20';              Value: 131),
    (Code: VK_F21;             Name: 'F21';              Value: 132),
    (Code: VK_F22;             Name: 'F22';              Value: 133),
    (Code: VK_F23;             Name: 'F23';              Value: 134),
    (Code: VK_F24;             Name: 'F24';              Value: 135),
    (Code: VK_NUMLOCK;         Name: 'NUMLOCK';          Value: $90),
    (Code: VK_SCROLL;          Name: 'SCROLL';           Value: $91),
    (Code: VK_LSHIFT;          Name: 'LSHIFT';           Value: $A0),
    (Code: VK_RSHIFT;          Name: 'RSHIFT';           Value: $A1),
    (Code: VK_LCONTROL;        Name: 'LCONTROL';         Value: $A2),
    (Code: VK_RCONTROL;        Name: 'RCONTROL';         Value: $A3),
    (Code: VK_LMENU;           Name: 'LMENU';            Value: $A4),
    (Code: VK_RMENU;           Name: 'RMENU';            Value: $A5),
    (Code: VK_BROWSER_BACK;    Name: 'BROWSER_BACK';     Value: $A6),
    (Code: VK_BROWSER_FORWARD; Name: 'BROWSER_FORWARD';  Value: $A7),
    (Code: VK_BROWSER_REFRESH; Name: 'BROWSER_REFRESH';  Value: $A8),
    (Code: VK_BROWSER_STOP;    Name: 'BROWSER_STOP';     Value: $A9),
    (Code: VK_BROWSER_SEARCH;  Name: 'BROWSER_SEARCH';   Value: $AA),
    (Code: VK_BROWSER_FAVORITES;Name: 'BROWSER_FAVORITES';Value: $AB),
    (Code: VK_BROWSER_HOME;    Name: 'BROWSER_HOME';     Value: $AC),
    (Code: VK_VOLUME_MUTE;     Name: 'VOLUME_MUTE';      Value: $AD),
    (Code: VK_VOLUME_DOWN;     Name: 'VOLUME_DOWN';      Value: $AE),
    (Code: VK_VOLUME_UP;       Name: 'VOLUME_UP';        Value: $AF),
    (Code: VK_MEDIA_NEXT_TRACK;Name: 'MEDIA_NEXT_TRACK'; Value: $B0),
    (Code: VK_MEDIA_PREV_TRACK;Name: 'MEDIA_PREV_TRACK'; Value: $B1),
    (Code: VK_MEDIA_STOP;      Name: 'MEDIA_STOP';       Value: $B2),
    (Code: VK_MEDIA_PLAY_PAUSE;Name: 'MEDIA_PLAY_PAUSE'; Value: $B3),
    (Code: VK_LAUNCH_MAIL;     Name: 'LAUNCH_MAIL';      Value: $B4),
    (Code: VK_LAUNCH_MEDIA_SELECT;Name: 'LAUNCH_MEDIA_SELECT';Value: $B5),
    (Code: VK_LAUNCH_APP1;     Name: 'LAUNCH_APP1';      Value: $B6),
    (Code: VK_LAUNCH_APP2;     Name: 'LAUNCH_APP2';      Value: $B7),
    (Code: VK_OEM_1;           Name: 'OEM_1';            Value: $BA),
    (Code: VK_OEM_PLUS;        Name: 'OEM_PLUS';         Value: $BB),
    (Code: VK_OEM_COMMA;       Name: 'OEM_COMMA';        Value: $BC),
    (Code: VK_OEM_MINUS;       Name: 'OEM_MINUS';        Value: $BD),
    (Code: VK_OEM_PERIOD;      Name: 'OEM_PERIOD';       Value: $BE),
    (Code: VK_OEM_2;           Name: 'OEM_2';            Value: $BF),
    (Code: VK_OEM_3;           Name: 'OEM_3';            Value: $C0),
    (Code: VK_OEM_4;           Name: 'OEM_4';            Value: $DB),
    (Code: VK_OEM_5;           Name: 'OEM_5';            Value: $DC),
    (Code: VK_OEM_6;           Name: 'OEM_6';            Value: $DD),
    (Code: VK_OEM_7;           Name: 'OEM_7';            Value: $DE),
    (Code: VK_OEM_8;           Name: 'OEM_8';            Value: $DF),
    (Code: VK_OEM_102;         Name: 'OEM_102';          Value: $E2),
    (Code: VK_PROCESSKEY;      Name: 'PROCESSKEY';       Value: $E7),
    (Code: VK_ATTN;            Name: 'ATTN';             Value: $F6),
    (Code: VK_CRSEL;           Name: 'CRSEL';            Value: $F7),
    (Code: VK_EXSEL;           Name: 'EXSEL';            Value: $F8),
    (Code: VK_EREOF;           Name: 'EREOF';            Value: $F9),
    (Code: VK_PLAY;            Name: 'PLAY';             Value: $FA),
    (Code: VK_ZOOM;            Name: 'ZOOM';             Value: $FB),
    (Code: VK_NONAME;          Name: 'NONAME';           Value: $FC),
    (Code: VK_PA1;             Name: 'PA1';              Value: $FD),
    (Code: VK_OEM_CLEAR;       Name: 'OEM_CLEAR';        Value: $FE),
    (Code: VK_HIGHESTVALUE;    Name: 'HIGHESTVALUE';     Value: $FFFF),
    (Code: VK_UNDEFINED;       Name: 'UNDEFINED';        Value: $FF),
    (Code: VK_LCL_EQUAL;       Name: 'LCL_EQUAL';        Value: VK_OEM_PLUS),
    (Code: VK_LCL_COMMA;       Name: 'LCL_COMMA';        Value: VK_OEM_COMMA),
    (Code: VK_LCL_POINT;       Name: 'LCL_POINT';        Value: VK_OEM_PERIOD),
    (Code: VK_LCL_SLASH;       Name: 'LCL_SLASH';        Value: VK_OEM_2),
    (Code: VK_LCL_SEMI_COMMA;  Name: 'LCL_SEMI_COMMA';   Value: VK_OEM_1),
    (Code: VK_LCL_MINUS;       Name: 'LCL_MINUS';        Value: VK_OEM_MINUS),
    (Code: VK_LCL_OPEN_BRACKET;Name: 'LCL_OPEN_BRACKET'; Value: VK_OEM_4),
    (Code: VK_LCL_CLOSE_BRACKET;Name: 'LCL_CLOSE_BRACKET';Value: VK_OEM_6),
    (Code: VK_LCL_BACKSLASH;   Name: 'LCL_BACKSLASH';    Value: VK_OEM_5),
    (Code: VK_LCL_TILDE;       Name: 'LCL_TILDE';        Value: VK_OEM_3),
    (Code: VK_LCL_QUOTE;       Name: 'LCL_QUOTE';        Value: VK_OEM_7),
    (Code: VK_LCL_ALT;         Name: 'LCL_ALT';          Value: VK_MENU),
    (Code: VK_LCL_LALT;        Name: 'LCL_LALT';         Value: VK_LMENU),
    (Code: VK_LCL_RALT;        Name: 'LCL_RALT';         Value: VK_RMENU),
    (Code: VK_LCL_CAPSLOCK;    Name: 'LCL_CAPSLOCK';     Value: VK_CAPITAL),
    (Code: VK_LCL_POWER;       Name: 'LCL_POWER';        Value: $100),
    (Code: VK_LCL_CALL;        Name: 'LCL_CALL';         Value: $101),
    (Code: VK_LCL_ENDCALL;     Name: 'LCL_ENDCALL';      Value: $102),
    (Code: VK_LCL_AT;          Name: 'LCL_AT';           Value: $103)
  );

implementation

function GetVKIndexByCode(Code: Word): Integer;
var
  i: Integer;
begin
  Result := -1;
  for i:=Low(VKcodes) to High(VKCodes) do begin
    if VKcodes[i].Code = Code then begin
      Result := i;
      Break;
    end;
  end;
end;

end.

